native zp_get_user_pipe(id)
native zp_get_user_laser(id)
native zp_get_user_sacos(id)
native zp_get_user_strip(id)
native zp_get_user_conf(id)
native zp_get_user_redem(id)
native zp_get_user_devastator(id)
native zp_get_user_angrybird(id)
native zp_get_user_plasma(id)
native zp_get_user_estado(id)
native zp_give_etheral(id)
enum
{
	OFFLINE = 0,
	REGISTRAR_USUARIO,
	REGISTRAR_PASSWORD,
	LOGUEAR_USUARIO,
	LOGUEAR_PASSWORD,
	CARGAR_DATOS,
	GUARDAR_DATOS,
	LOGUEADO
}